### ISSUE TITLE
Error message on installation

### ISSUE THREAD

**Issue by haslinger** [coding-chimp/podlove-web-player-rails#1]
`rails g podlove-web-player-rails:install`
causes an error message on Rails 4.0.13: 
`Could not find generator podlove-web-player-rails:install.`
The assets seem to be available though ....

**Comment by coding-chimp** [comment]
Sorry it took me so long to answer!

Looks like I made a typo in the README.
It should actually be `rails g podlove_web_player_rails:install`.
I updated the README accordingly. Thanks!
