### ISSUE TITLE
Cannot read property 'msie' of undefined

### ISSUE THREAD

**Issue by haslinger** [coding-chimp/podlove-web-player-rails#2]
The currently used  version of hashchange.min.js is not compatible with current versions of jQuery.
It causes `Cannot read property 'msie' of undefined` when loaded as it uses `$.browser` which is deprecated as of JQuery 1.9.
I could overcome this with the use of jquery-migrate, but I think it should be fixed.

**Comment by coding-chimp** [comment]
I'm just bundling the assets needed for the podlove-web-player into a gem and I am using the assets of the latests stable release of the player.

So while I agree that this should be fixed, this is probably more a issue for the folks over at the [podlove-web-player](https://github.com/podlove/podlove-web-player).
